#!/usr/bin/env bash
# ============================================================================
# generate-object-list.sh
# export-ddl.sh が生成した CSV (objects.csv) を読み、
# agent/object_list.ini フォーマットに変換する。
#
# 入力 CSV (objects.csv):
#   object_type,schema_name,object_name,is_encrypted_or_unavailable
#   SQL_STORED_PROCEDURE,dbo,usp_xxx,0
#   SQL_SCALAR_FUNCTION,dbo,fn_yyy,0
#   ...
#
# 出力 (object_list.ini):
#   PROCEDURE dbo.usp_xxx
#   FUNCTION  dbo.fn_yyy
#
# Usage:
#   ./generate-object-list.sh                                # デフォルト入出力
#   ./generate-object-list.sh INPUT.csv                      # 入力指定
#   ./generate-object-list.sh INPUT.csv OUTPUT.ini           # 入出力指定
#   INCLUDE_ENCRYPTED=1 ./generate-object-list.sh ...        # WITH ENCRYPTION も含める
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_INPUT="$SCRIPT_DIR/../output/objects.csv"
DEFAULT_OUTPUT="$SCRIPT_DIR/../output/object_list.ini"

INPUT="${1:-$DEFAULT_INPUT}"
OUTPUT="${2:-$DEFAULT_OUTPUT}"
INCLUDE_ENCRYPTED="${INCLUDE_ENCRYPTED:-0}"

if [[ ! -f "$INPUT" ]]; then
    echo "[ERROR] Input CSV not found: $INPUT" >&2
    echo "        Run export-ddl.sh first to generate objects.csv" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUTPUT")"

# type_desc → object_list.ini キーワード変換マップ
# CLR は AI 変換できないため警告コメント付きで出力
type_to_keyword() {
    case "$1" in
        SQL_STORED_PROCEDURE)              echo "PROCEDURE" ;;
        SQL_SCALAR_FUNCTION)               echo "FUNCTION"  ;;
        SQL_INLINE_TABLE_VALUED_FUNCTION)  echo "FUNCTION"  ;;
        SQL_TABLE_VALUED_FUNCTION)         echo "FUNCTION"  ;;
        CLR_SCALAR_FUNCTION)               echo "FUNCTION_CLR" ;;
        CLR_TABLE_VALUED_FUNCTION)         echo "FUNCTION_CLR" ;;
        SQL_TRIGGER)                       echo "TRIGGER"   ;;
        VIEW)                              echo "VIEW"      ;;
        *)                                 echo ""          ;;
    esac
}

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S %Z')
TOTAL_IN=0
EMITTED=0
SKIPPED_ENCRYPTED=0
SKIPPED_CLR=0
SKIPPED_OTHER=0

{
    echo "# Auto-generated by extraction/scripts/generate-object-list.sh"
    echo "# Generated at: $TIMESTAMP"
    echo "# Source CSV:   $INPUT"
    echo "#"
    echo "# Format: <ObjectType> <SchemaName>.<ObjectName>"
    echo "# 行頭に '#' を付けると変換対象から除外されます。"
    echo

    while IFS=, read -r type_desc schema_name object_name is_encrypted; do
        # ヘッダ行スキップ
        if [[ "$type_desc" == "object_type" ]]; then
            continue
        fi
        [[ -z "$type_desc" ]] && continue
        TOTAL_IN=$((TOTAL_IN + 1))

        keyword=$(type_to_keyword "$type_desc")

        # CLR は AI 変換不可 → コメントアウトで残す
        if [[ "$keyword" == "FUNCTION_CLR" ]]; then
            echo "# [SKIP-CLR] $type_desc not supported by AI converter: $schema_name.$object_name"
            SKIPPED_CLR=$((SKIPPED_CLR + 1))
            continue
        fi

        if [[ -z "$keyword" ]]; then
            echo "# [SKIP-UNKNOWN] type_desc=$type_desc: $schema_name.$object_name"
            SKIPPED_OTHER=$((SKIPPED_OTHER + 1))
            continue
        fi

        # WITH ENCRYPTION で保護されている = 定義取得不可
        if [[ "$is_encrypted" == "1" ]]; then
            if [[ "$INCLUDE_ENCRYPTED" == "1" ]]; then
                echo "# [WARN-ENCRYPTED] $keyword $schema_name.$object_name (definition unavailable, will fail)"
                echo "$keyword $schema_name.$object_name"
            else
                echo "# [SKIP-ENCRYPTED] $keyword $schema_name.$object_name (WITH ENCRYPTION, set INCLUDE_ENCRYPTED=1 to include)"
            fi
            SKIPPED_ENCRYPTED=$((SKIPPED_ENCRYPTED + 1))
            continue
        fi

        echo "$keyword $schema_name.$object_name"
        EMITTED=$((EMITTED + 1))
    done < "$INPUT"
} > "$OUTPUT"

# サマリ出力 (stderr)
{
    echo "[INFO] Generated: $OUTPUT"
    echo "[INFO]   Input rows:                    $TOTAL_IN"
    echo "[INFO]   Emitted (convertible):         $EMITTED"
    echo "[INFO]   Skipped (encrypted):           $SKIPPED_ENCRYPTED"
    echo "[INFO]   Skipped (CLR, unsupported):    $SKIPPED_CLR"
    echo "[INFO]   Skipped (other):               $SKIPPED_OTHER"
} >&2
